export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      matches: {
        Row: {
          id: string;
          source: string;
          game: "cs2" | "valorant" | "lol";
          provider_match_id: string;
          name: string;
          begin_at: string;
          end_at: string | null;
          display_date: string;
          status: "not_started" | "running" | "finished" | "postponed" | "cancelled";
          league: string | null;
          league_image_url: string | null;
          tournament: string | null;
          tournament_type: string | null;
          tournament_country: string | null;
          tournament_region: string | null;
          tournament_tier: string | null;
          tournament_prizepool: string | null;
          has_bracket: boolean | null;
          best_of: number | null;
          match_type: string | null;
          rescheduled: boolean | null;
          detailed_stats_available: boolean | null;
          draw: boolean | null;
          forfeit: boolean | null;
          winner_team_id: string | null;
          winner_name: string | null;
          teams: Json;
          score: Json;
          games: Json;
          stream_url: string | null;
          replay_url: string | null;
          serie: string | null;
          stage: string | null;
          raw_payload: Json | null;
          provider_updated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          source: string;
          game: "cs2" | "valorant" | "lol";
          provider_match_id: string;
          name: string;
          begin_at: string;
          end_at?: string | null;
          display_date: string;
          status: "not_started" | "running" | "finished" | "postponed" | "cancelled";
          league?: string | null;
          league_image_url?: string | null;
          tournament?: string | null;
          tournament_type?: string | null;
          tournament_country?: string | null;
          tournament_region?: string | null;
          tournament_tier?: string | null;
          tournament_prizepool?: string | null;
          has_bracket?: boolean | null;
          best_of?: number | null;
          match_type?: string | null;
          rescheduled?: boolean | null;
          detailed_stats_available?: boolean | null;
          draw?: boolean | null;
          forfeit?: boolean | null;
          winner_team_id?: string | null;
          winner_name?: string | null;
          teams?: Json;
          score?: Json;
          games?: Json;
          stream_url?: string | null;
          replay_url?: string | null;
          serie?: string | null;
          stage?: string | null;
          raw_payload?: Json | null;
          provider_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["matches"]["Insert"]>;
        Relationships: [];
      };
      match_fetch_windows: {
        Row: {
          id: string;
          source: string;
          game: "cs2" | "valorant" | "lol";
          from_date: string;
          to_date: string;
          status_group: string;
          last_synced_at: string | null;
          expires_at: string | null;
          last_error_code: string | null;
          last_error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          source: string;
          game: "cs2" | "valorant" | "lol";
          from_date: string;
          to_date: string;
          status_group: string;
          last_synced_at?: string | null;
          expires_at?: string | null;
          last_error_code?: string | null;
          last_error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["match_fetch_windows"]["Insert"]>;
        Relationships: [];
      };
      sync_runs: {
        Row: {
          id: string;
          source: string;
          game: "cs2" | "valorant" | "lol";
          from_date: string;
          to_date: string;
          status_group: string;
          started_at: string;
          finished_at: string | null;
          success: boolean;
          fetched_count: number;
          upserted_count: number;
          error_code: string | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          source: string;
          game: "cs2" | "valorant" | "lol";
          from_date: string;
          to_date: string;
          status_group: string;
          started_at?: string;
          finished_at?: string | null;
          success?: boolean;
          fetched_count?: number;
          upserted_count?: number;
          error_code?: string | null;
          error_message?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["sync_runs"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
